"""Bookmark model — anonymous per-client CVE bookmarks.

Kestrel has no auth; bookmarks are scoped by an opaque client_id (UUID
generated by the browser and sent via the `X-Client-Id` header).
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Index, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class Bookmark(Base):
    __tablename__ = "bookmarks"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    client_id: Mapped[str] = mapped_column(String(64), nullable=False)
    cve_id: Mapped[str] = mapped_column(String(32), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    __table_args__ = (
        UniqueConstraint("client_id", "cve_id", name="uq_bookmark_client_cve"),
        Index("ix_bookmark_client", "client_id"),
    )
